# Magic Square
https://fr.wikipedia.org/wiki/Carr%C3%A9_magique_(math%C3%A9matiques)

In [4]:
from squaredata import *
import numpy as np

In [3]:
square_ok_12

[[138, 8, 17, 127, 114, 32, 41, 103, 90, 56, 65, 79],
 [19, 125, 140, 6, 43, 101, 116, 30, 67, 77, 92, 54],
 [128, 18, 7, 137, 104, 42, 31, 113, 80, 66, 55, 89],
 [5, 139, 126, 20, 29, 115, 102, 44, 53, 91, 78, 68],
 [136, 10, 15, 129, 112, 34, 39, 105, 88, 58, 63, 81],
 [21, 123, 142, 4, 45, 99, 118, 28, 69, 75, 94, 52],
 [130, 16, 9, 135, 106, 40, 33, 111, 82, 64, 57, 87],
 [3, 141, 124, 22, 27, 117, 100, 46, 51, 93, 76, 70],
 [134, 12, 13, 131, 110, 36, 37, 107, 86, 60, 61, 83],
 [23, 121, 144, 2, 47, 97, 120, 26, 71, 73, 96, 50],
 [132, 14, 11, 133, 108, 38, 35, 109, 84, 62, 59, 85],
 [1, 143, 122, 24, 25, 119, 98, 48, 49, 95, 74, 72]]

In [5]:
np_square_ok_3 = np.array(square_ok_3)
np_square_ok_3

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

In [6]:
print(np_square_ok_3.shape)
print(np_square_ok_3.flags)
print(np_square_ok_3.dtype)

(3, 3)
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

int32


In [7]:
12**2

144

## Vérifier que le carré np_square_ok_3 est magique:
- somme des lignes
- somme des colonnes
- somme des "diagonales"
- bonus: en utilisant les nombres (1 seule fois) entre 1 et n**2

In [16]:
square = np_square_ok_3
square

array([[8, 1, 6],
       [3, 5, 7],
       [4, 9, 2]])

In [13]:
n = len(square)
n

3

In [14]:
n, m = square.shape
assert n == m
n

3

In [17]:
# magic sum
ms = n*(n**2+1)//2
ms

15

In [23]:
np.sum

<function numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

In [24]:
square.sum

<function ndarray.sum>

In [25]:
square.sum(axis=1)

array([15, 15, 15])

In [26]:
square.sum(axis=1) == ms

array([ True,  True,  True])

In [27]:
# NB: all (equivalent and for n elements)
# NB: any (equivalent or for n elements)
np.all(square.sum(axis=1) == ms)

True